name: Package

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  package:
    uses: normlanguage/registry/.github/workflows/package.yml@92f1345e5cb6722b6b726f3afed5cd2aa08754df
    with:
      norm-version: 0.25.0
      runner: windows-2025
