name: Package

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  package:
    uses: normlanguage/registry/.github/workflows/package.yml@078285bf20bb058b7f9c0646b302332cac88adea
    with:
      norm-version: 0.24.0
      runner: windows-2025
